- rule: field_requires_description
  severity: warning
- rule: view_with_many_fields_requires_fields_hidden_by_default
  severity: warning
- rule: view_with_dimensions_and_measures_has_one_primary_key
  severity: warning
- rule: primary_key_is_first_dimension_in_view
  severity: error
- rule: dimension_group_of_type_time_requires_datatype
  severity: warning
- rule: dimension_group_of_type_time_requires_timeframes
  severity: warning
- rule: explore_joins_require_relationship
  severity: error
- rule: explore_requires_description
  severity: error
- rule: explore_joins_contain_many_to_many_relationship
  severity: warning
- rule: explore_requires_label
  severity: warning
- rule: field_name_is_snake_case
  severity: error
- rule: view_name_is_snake_case
  severity: error
- rule: explore_requires_always_filter
  severity: warning
- rule: explore_requires_fields
  severity: error
- rule: view_requires_label
  severity: warning
- rule: dimension_group_name_should_not_end_with_date_or_time
  severity: warning
- rule: yesno_field_label_should_not_contain_yesno
  severity: warning
- rule: count_measure_name_must_start_with_count
  severity: warning
- rule: average_measure_name_must_start_with_avg_or_average
  severity: warning
- rule: sum_measure_name_must_start_with_sum_or_total
  severity: warning
- rule: yesno_field_name_must_start_with_is_or_has
  severity: warning
- rule: explore_tag_requires_owner
  severity: error
- rule: include_should_not_have_views_with_wildcard
  severity: warning
- rule: dimension_group_name_should_not_end_with
  severity: warning
  param_sets:
    - search_terms:
        - _day_pt
- rule: field_sql_html_requires_user_attribute_when_search_terms_found_exact
  severity: ignore
