name: Lint Project

on:
  pull_request:
    branches: [master]

jobs:
  lookml_linter:
    runs-on: ubuntu-latest
    name: LookML Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run LookML Liniter
        uses: rbob86/lookml-linter@main
