name: Lint Project

on:
  push:
  pull_request:
    branches: [master]

jobs:
  lookml_linter:
    runs-on: ubuntu-latest
    name: LookML Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Run LookML Liniter
        uses: rbob86/lookml-linter@v16
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Commit linter log file
        if: success() || failure()
        uses: EndBug/add-and-commit@v9
