name: Lint Project

on:
  push
  pull_request:
    branches: [master]

jobs:
  lookml_linter:
    runs-on: ubuntu-latest
    name: LookML Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run LookML Liniter
        uses: rbob86/lookml-linter@main
      - name: Commit linter log file
        uses: EndBug/add-and-commit@v9
