name: Lint Project

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches: [master]

jobs:
  lookml_linter:
    runs-on: ubuntu-latest
    name: LookML Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: .github
          since_last_remote_commit: true
      - name: Run LookML Linter
        id: lookml-linter
        uses: rbob86/lookml-linter@main
        with:
          filepaths: ${{ steps.changed-files.outputs.all_changed_files }}
          saveOutputToFile: false
      - uses: mshick/add-pr-comment@v2
        with:
          message: ${{ steps.lookml-linter.outputs.error_log }}
        if: github.event_name == 'pull_request'
      - name: Commit linter log file
        if: github.event_name != 'pull_request' && (success() || failure())
        uses: EndBug/add-and-commit@v9
